# Generated by Django 5.2.15 on 2026-06-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_studentexamsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=45, help_text='Để trống nếu không giới hạn thời gian', null=True),
        ),
    ]
