# Generated by Django 5.2.15 on 2026-06-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_profile_full_name_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamsession',
            name='shuffled_choice_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamsession',
            name='shuffled_question_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
